# Generated by Django 6.0.5 on 2026-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagejob',
            name='callback_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagejob',
            name='callback_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagejob',
            name='callback_status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagejob',
            name='callback_url',
            field=models.URLField(blank=True),
        ),
    ]
