"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-23g!vqdf%0&pvbx4^__6@hnb%3u$_q8b_yt-$q%4lzu@ep5r42'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        '127.0.0.1,localhost,172.17.0.1,172.18.0.1',
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'images',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PREPROCESSING_CALLBACK_TIMEOUT_SECONDS = float(
    os.environ.get('PREPROCESSING_CALLBACK_TIMEOUT_SECONDS', '10')
)
TOR_SERVICE_TOKEN = os.environ.get('TOR_SERVICE_TOKEN', 'local-dev-token')
TOR_MODEL_WEIGHTS_PATH = os.environ.get(
    'TOR_MODEL_WEIGHTS_PATH',
    str(BASE_DIR / 'patch_baseline_final.pth'),
)
TOR_INFERENCE_THRESHOLD = float(os.environ.get('TOR_INFERENCE_THRESHOLD', '0.380'))
TOR_INFERENCE_DEVICE = os.environ.get('TOR_INFERENCE_DEVICE', '')
TOR_SIGNATURE_MODEL_WEIGHTS_PATH = os.environ.get(
    'TOR_SIGNATURE_MODEL_WEIGHTS_PATH',
    str(BASE_DIR / 'siamese_resnet18_finetuned_no_leakage.pth'),
)
TOR_SIGNATURE_REFERENCES_ROOT = os.environ.get(
    'TOR_SIGNATURE_REFERENCES_ROOT',
    str(BASE_DIR / 'signature_references'),
)
TOR_SIGNATURE_DISTANCE_THRESHOLD = float(os.environ.get('TOR_SIGNATURE_DISTANCE_THRESHOLD', '0.3771'))
TOR_SIGNATURE_DEVICE = os.environ.get('TOR_SIGNATURE_DEVICE', '')
